### ISSUE TITLE
not able to open an optiSLang instance when using an opx input

### ISSUE THREAD

**Issue by ansDArnold** [ansys/pyoptislang#243]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

output:
```
===============================================================================
       NEW SESSION - 02/06/2024, 11:34:09
===============================================================================

LEVEL - MODULE - CLASS - FUNCTION - MESSAGE
Traceback (most recent call last):
  File "C:\Users\daarnold\OneDrive - ANSYS, Inc\projects\AZ_MixingApp\submit_SCP\run_fluent_job.py", line 10, in <module>
    with Optislang(opx_project_definition_file=opx_path, ini_timeout=300) as osl:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daarnold\OneDrive - ANSYS, Inc\projects\AZ_MixingApp\submit_SCP\.venv\Lib\site-packages\ansys\optislang\core\optislang.py", line 244, in __init__
    self.__osl_server: OslServer = self.__init_osl_server("tcp")
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daarnold\OneDrive - ANSYS, Inc\projects\AZ_MixingApp\submit_SCP\.venv\Lib\site-packages\ansys\optislang\core\optislang.py", line 270, in __init_osl_server
    return TcpOslServer(
           ^^^^^^^^^^^^^
  File "C:\Users\daarnold\OneDrive - ANSYS, Inc\projects\AZ_MixingApp\submit_SCP\.venv\Lib\site-packages\ansys\optislang\core\tcp_osl_server.py", line 1198, in __init__
    self._start_local(ini_timeout, shutdown_on_finished)
  File "C:\Users\daarnold\OneDrive - ANSYS, Inc\projects\AZ_MixingApp\submit_SCP\.venv\Lib\site-packages\ansys\optislang\core\tcp_osl_server.py", line 3322, in _start_local
    raise RuntimeError("Cannot get optiSLang server port.")
RuntimeError: Cannot get optiSLang server port.
```

### 📝 Steps to reproduce

``` 
from ansys.optislang.core import Optislang
import pathlib
import tempfile

ref_dir = pathlib.Path(__file__).parent / 'ref'
osl_proj_dir = pathlib.Path(__file__).parent / 'optiSLang_projects'
opx_path = ref_dir / 'submit_fluent.opx'
opf_path = tempfile.mktemp(suffix='.opf', prefix='submit_osl_', dir=osl_proj_dir)

with Optislang(opx_project_definition_file=opx_path, ini_timeout=300) as osl:
    print(osl)
    osl.save_as(file_path=opf_path)
```

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

Product name: optiSLang
Version: 24.1.0 (2657)
PyOptiSLang: 0.5.1

### 🐍 Which Python version are you using?

3.8

### 📦 Installed packages

```shell
ansys-optislang-core==0.5.1
Deprecated==1.2.14
importlib-metadata==6.11.0
psutil==5.9.8
wrapt==1.16.0
zipp==3.17.0
```

**Comment by PanekOndrej** [comment]
Hi @ansDArnold, I tried with a simple opx file and it works fine for me. I get the same error as you have, if I use invalid opx file or invalid path. I would suggest to try following steps:

- Check whether the `opx` file is readable from optiSLang GUI.

- Enter the path directly either as a raw string `opx_path = r"C:\Users\xxx\test_file.opx"` or pathlib.Path `opx_path = Path(r"C:\Users\xxx\test_file.opx)`.

- Raise `loglevel='DEBUG'` to get detailed info about what is going on.

Please let me know, if the problem persists.
